import type { Bilingual } from "./catalog";
import type { FulfillmentType, OrderSource, OrderStatus } from "./orders";

export type AdminOrderItemDetail = {
  id: string;
  cake_id: string;
  size_id: string | null;
  tier_id: string | null;
  shape_id: string | null;
  is_fifty_fifty: boolean;
  topper_id: string | null;
  topper_color_id: string | null;
  text_on_cake: string | null;
  text_on_board: string | null;
  notes: string | null;
  quantity: number;
  unit_base_price: number;
  price_modifiers_total: number;
  line_estimate: number;
  final_price: number | null;
  is_fake: boolean;
  fake_size_cm: number | null;
  fake_shape_id: string | null;
  reference_image_url: string | null;
  reference_image_public_id: string | null;
  color_arrangement_notes: string | null;
  cakes: { id: string; name: Bilingual; primary_image_url: string | null; category_id: string } | null;
  sizes: { min_qty: number; max_qty: number; unit: "servings" | "quantity" | "cm" } | null;
  tiers: { tier_count: number } | null;
  shape: { id: string; name: Bilingual } | null;
  fake_shape: { id: string; name: Bilingual } | null;
  topper: { id: string; name: Bilingual; has_color_variants: boolean } | null;
  topper_color: { id: string; name: Bilingual; hex_code: string | null } | null;
  order_item_flavors: { flavor_id: string; position: number; flavors: { name: Bilingual } }[];
  order_item_colors: { color_id: string; sort_order: number; colors: { name: Bilingual; hex_code: string | null } }[];
};

export type AdminOrderDetail = {
  id: string;
  order_number: string;
  customer_id: string | null;
  guest_name: string | null;
  contact_phone: string | null;
  contact_phone_method: "call" | "whatsapp" | "both" | null;
  status: OrderStatus;
  fulfillment_type: FulfillmentType;
  delivery_address: string | null;
  fulfillment_date: string;
  notes: string | null;
  subtotal_estimate: number;
  delivery_price: number;
  discount_amount: number;
  final_price: number | null;
  source: OrderSource;
  created_at: string;
  profiles: { first_name: string | null; last_name: string | null } | null;
  delivery_areas: { name: Bilingual } | null;
};
